### PR TITLE
Made some sort of base line for the algorithmn

### PR DESCRIPTION
**Pull request by travisle22**
More varaiables?

### CODE REVIEW

**Review by qabach — APPROVED** [review]
looks good to me

**Review by anhtruong18 — CHANGES_REQUESTED** [review]
Can you add the setters for the Stats structs. Ex: Cannot do Node->GetJob().stats.waittime at the same time. Thank you

**Review by anhtruong18 — APPROVED** [review]
look great

**Comment by qabach** [comment]
I will go ahead and merge this, since there is no conflict.

**Pull request merged**
